credentials:
  usernames:
    member001:
      email: member@example.com
      name: テスト会員
      password: "$2b$12$5k1ueFP3NfmKqaVOBspyBumxTpy.P801fZXDHfnL4Aq7FH7rlY7yW"
cookie:
  expiry_days: 3
  key: test_app_key
  name: test_app_cookie
